require 'rubygems'
gem 'rails', '~> 2.3.8'
gem 'activesupport'
gem 'activerecord'
gem 'actionpack'
require 'active_support'
require 'active_support/test_case'
require "active_record"
require 'yaml'
require File.dirname(__FILE__) + '/../models/blog'
require File.dirname(__FILE__) + '/../models/user'
RAILS_ENV = 'test'
